### PR TITLE
Supresses the IO Exception of convert-source-map

### LINKED ISSUE #5: IO exception
There can be an io exception when there is no sourcemap given nor there is a source map file.
The following stacktrace will be reproduced (I have ommited some parts of the file path) :
```
ERROR in ./src/main/javascript/app/components/path/traffic-diensten.component.js
Module build failed (from ./node_modules/coverage-istanbul-loader/lib/index.js):
Error: An error occurred while trying to read the map file at \path\src\main\javascript\app\components\path\traffic-diensten.component.js.map
Error: ENOENT: no such file or directory, open '\path\src\main\javascript\app\components\path\traffic-diensten.component.js.map'
at readFromFileMap (\path\node_modules\convert-source-map\index.js:40:11)
at new Converter (\path\node_modules\convert-source-map\index.js:47:32)
at Object.exports.fromMapFileComment (\path\node_modules\convert-source-map\index.js:110:10)
at Object.exports.fromMapFileSource (\path\node_modules\convert-source-map\index.js:122:22)
at Object.default_1 (\path\node_modules\coverage-istanbul-loader\src\index.ts:28:26)
@ ./src/main/javascript/app/components/overzichten/overzichten.module.ts 92:0-94 108:807-840
@ ./src/main/javascript/app/components/components.ts
@ ./src/main/javascript/app/app.angularjs.module.ts
@ ./src/main/javascript/flow-tests.ts
```

See also: https://github.com/JS-DevTools/coverage-istanbul-loader/blob/master/src/index.ts#L25

### PR DESCRIPTION
**Pull request by Pouja**
The [IO Exception](https://github.com/thlorenz/convert-source-map/blob/master/index.js#L40) occurs when in the webpack pipeline some files have the .map counterpart but some don't. In [our case](https://github.com/angular/angular-cli/issues/16854) it happens when some of the files have `.js` extension where others have `.ts`

If the user enables the stats of webpack, he/she would still see the warnings.

Closes #5

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -20,14 +20,21 @@ export default function(this: loader.LoaderContext, source: string, sourceMap?:
...
-      // Use the inline source map
-      sourceMap = inlineSourceMap.sourcemap as RawSourceMap;
+      if (inlineSourceMap) {
+        // Use the inline source map
+        sourceMap = inlineSourceMap.sourcemap as RawSourceMap;
+      }
+    }
+  } catch (e) {
+    // Exception is thrown by fromMapFileSource when there is no source map file
+    if (typeof e === "string" || e instanceof Error) {
```
Comment (JamesMessinger) [inline src/index.ts]: This will suppress **all** errors, not just the ones related to a missing source map.  Please check specifically for the missing-sourcemap error, and only suppress that one.  Any other error should be re-thrown.

**Review by JamesMessinger — CHANGES_REQUESTED** [review]
Thanks for the PR, @Pouja!  It looks good, but there's one change I'd like you to make to narrow the scope

File: src/index.ts (hunk 1 above)
Comment (Pouja) [reply src/index.ts]: Solved it with `e.message.includes("An error occurred while trying to read the map file at")`

Comment (BojanKogoj) [reply src/index.ts]: @JamesMessinger Can you take a look at this?
